version: '3.8'

services:
  php:
    build: .
    container_name: my_symfony_app
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      APP_ENV: dev
      SYMFONY_DOTENV_VARS: APP_ENV
    networks:
      - symfony_net

  db:
    image: mysql:5.7
    container_name: my_symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_net

networks:
  symfony_net:
    driver: bridge

volumes:
  db_data:
